# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_window.ui',
# licensing of '.\ui\main_window.ui' applies.
#
# Created: Tue Jul 23 15:37:14 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from ui import UiTreeWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_api = QtWidgets.QHBoxLayout()
        self.layout_api.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_api.setContentsMargins(-1, -1, -1, 10)
        self.layout_api.setObjectName("layout_api")
        self.lbl_api = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api.sizePolicy().hasHeightForWidth())
        self.lbl_api.setSizePolicy(sizePolicy)
        self.lbl_api.setObjectName("lbl_api")
        self.layout_api.addWidget(self.lbl_api)
        self.cmb_api = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_api.setEnabled(False)
        self.cmb_api.setMinimumSize(QtCore.QSize(44, 0))
        self.cmb_api.setObjectName("cmb_api")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.layout_api.addWidget(self.cmb_api)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_api.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layout_api)
        self.layout_source = QtWidgets.QHBoxLayout()
        self.layout_source.setSpacing(6)
        self.layout_source.setObjectName("layout_source")
        self.lbl_source = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_source.sizePolicy().hasHeightForWidth())
        self.lbl_source.setSizePolicy(sizePolicy)
        self.lbl_source.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_source.setObjectName("lbl_source")
        self.layout_source.addWidget(self.lbl_source)
        self.le_source = QtWidgets.QLineEdit(self.centralwidget)
        self.le_source.setEnabled(True)
        self.le_source.setReadOnly(True)
        self.le_source.setObjectName("le_source")
        self.layout_source.addWidget(self.le_source)
        self.btn_source = QtWidgets.QToolButton(self.centralwidget)
        self.btn_source.setObjectName("btn_source")
        self.layout_source.addWidget(self.btn_source)
        self.verticalLayout_2.addLayout(self.layout_source)
        self.layout_selector = QtWidgets.QHBoxLayout()
        self.layout_selector.setSpacing(6)
        self.layout_selector.setObjectName("layout_selector")
        self.lbl_target = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_target.sizePolicy().hasHeightForWidth())
        self.lbl_target.setSizePolicy(sizePolicy)
        self.lbl_target.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_target.setObjectName("lbl_target")
        self.layout_selector.addWidget(self.lbl_target)
        self.le_target = QtWidgets.QLineEdit(self.centralwidget)
        self.le_target.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_target.sizePolicy().hasHeightForWidth())
        self.le_target.setSizePolicy(sizePolicy)
        self.le_target.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.le_target.setReadOnly(True)
        self.le_target.setObjectName("le_target")
        self.layout_selector.addWidget(self.le_target)
        self.btn_target = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_target.sizePolicy().hasHeightForWidth())
        self.btn_target.setSizePolicy(sizePolicy)
        self.btn_target.setObjectName("btn_target")
        self.layout_selector.addWidget(self.btn_target)
        self.verticalLayout_2.addLayout(self.layout_selector)
        self.fields_selector = QtWidgets.QGridLayout()
        self.fields_selector.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.fields_selector.setContentsMargins(-1, -1, -1, 0)
        self.fields_selector.setObjectName("fields_selector")
        self.list_source = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_source.sizePolicy().hasHeightForWidth())
        self.list_source.setSizePolicy(sizePolicy)
        self.list_source.setAcceptDrops(False)
        self.list_source.setStyleSheet("")
        self.list_source.setDragEnabled(False)
        self.list_source.setObjectName("list_source")
        self.fields_selector.addWidget(self.list_source, 1, 0, 1, 1)
        self.list_merged = UiTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_merged.sizePolicy().hasHeightForWidth())
        self.list_merged.setSizePolicy(sizePolicy)
        self.list_merged.setAcceptDrops(False)
        self.list_merged.setObjectName("list_merged")
        self.fields_selector.addWidget(self.list_merged, 1, 1, 1, 1)
        self.list_target = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_target.sizePolicy().hasHeightForWidth())
        self.list_target.setSizePolicy(sizePolicy)
        self.list_target.setAcceptDrops(False)
        self.list_target.setDragEnabled(False)
        self.list_target.setObjectName("list_target")
        self.fields_selector.addWidget(self.list_target, 1, 2, 1, 1)
        self.layout_treeButtons = QtWidgets.QHBoxLayout()
        self.layout_treeButtons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_treeButtons.setObjectName("layout_treeButtons")
        self.btn_applyA = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/icons/chevrons-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_applyA.setIcon(icon)
        self.btn_applyA.setObjectName("btn_applyA")
        self.layout_treeButtons.addWidget(self.btn_applyA)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_treeButtons.addItem(spacerItem1)
        self.btn_expandAll = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/icons/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_expandAll.setIcon(icon1)
        self.btn_expandAll.setObjectName("btn_expandAll")
        self.layout_treeButtons.addWidget(self.btn_expandAll)
        self.btn_collapseAll = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/icons/minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_collapseAll.setIcon(icon2)
        self.btn_collapseAll.setObjectName("btn_collapseAll")
        self.layout_treeButtons.addWidget(self.btn_collapseAll)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_treeButtons.addItem(spacerItem2)
        self.btn_applyB = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/icons/chevrons-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_applyB.setIcon(icon3)
        self.btn_applyB.setObjectName("btn_applyB")
        self.layout_treeButtons.addWidget(self.btn_applyB)
        self.fields_selector.addLayout(self.layout_treeButtons, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.fields_selector)
        self.layout_filter = QtWidgets.QHBoxLayout()
        self.layout_filter.setSpacing(6)
        self.layout_filter.setObjectName("layout_filter")
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_filter.addItem(spacerItem3)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(96, 36))
        self.btn_start.setObjectName("btn_start")
        self.layout_filter.addWidget(self.btn_start)
        self.verticalLayout_2.addLayout(self.layout_filter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 20))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.accionPlaceHolder = QtWidgets.QAction(MainWindow)
        self.accionPlaceHolder.setEnabled(False)
        self.accionPlaceHolder.setObjectName("accionPlaceHolder")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionMerge = QtWidgets.QAction(MainWindow)
        self.actionMerge.setObjectName("actionMerge")
        self.actionExpand_All = QtWidgets.QAction(MainWindow)
        self.actionExpand_All.setObjectName("actionExpand_All")
        self.actionCollapse_All = QtWidgets.QAction(MainWindow)
        self.actionCollapse_All.setObjectName("actionCollapse_All")
        self.actionApplyAvalues = QtWidgets.QAction(MainWindow)
        self.actionApplyAvalues.setObjectName("actionApplyAvalues")
        self.actionApplyBValues = QtWidgets.QAction(MainWindow)
        self.actionApplyBValues.setObjectName("actionApplyBValues")
        self.menuSettings.addAction(self.accionPlaceHolder)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionMerge)
        self.menuView.addAction(self.actionExpand_All)
        self.menuView.addAction(self.actionCollapse_All)
        self.menuEdit.addAction(self.actionApplyAvalues)
        self.menuEdit.addAction(self.actionApplyBValues)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.cmb_api.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cmb_api, self.btn_target)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SF Profile Merger by @f1r3f0x -- WIP", None, -1))
        self.lbl_api.setText(QtWidgets.QApplication.translate("MainWindow", "(TODO) Base Api Version:", None, -1))
        self.cmb_api.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "45", None, -1))
        self.cmb_api.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "44", None, -1))
        self.cmb_api.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "43", None, -1))
        self.cmb_api.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "42", None, -1))
        self.cmb_api.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "41", None, -1))
        self.cmb_api.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "40", None, -1))
        self.cmb_api.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "39", None, -1))
        self.cmb_api.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "38", None, -1))
        self.cmb_api.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "37", None, -1))
        self.cmb_api.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "36", None, -1))
        self.cmb_api.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "35", None, -1))
        self.cmb_api.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "34", None, -1))
        self.cmb_api.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "33", None, -1))
        self.cmb_api.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "32", None, -1))
        self.cmb_api.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.lbl_source.setText(QtWidgets.QApplication.translate("MainWindow", "Profile A", None, -1))
        self.btn_source.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lbl_target.setText(QtWidgets.QApplication.translate("MainWindow", "Profile B", None, -1))
        self.btn_target.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.list_source.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "[Left Click] to merge values", None, -1))
        self.list_source.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Profile A", None, -1))
        self.list_merged.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "[Right Click] to toggle values", None, -1))
        self.list_merged.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Profile Merged", None, -1))
        self.list_target.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "[Left Click] to merge value", None, -1))
        self.list_target.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Profile B", None, -1))
        self.btn_applyA.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_expandAll.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_collapseAll.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_applyB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_start.setText(QtWidgets.QApplication.translate("MainWindow", "Save Merged", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "?", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.accionPlaceHolder.setText(QtWidgets.QApplication.translate("MainWindow", "TODO", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionMerge.setText(QtWidgets.QApplication.translate("MainWindow", "Merge", None, -1))
        self.actionMerge.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Create merged profile and save", None, -1))
        self.actionMerge.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+M", None, -1))
        self.actionExpand_All.setText(QtWidgets.QApplication.translate("MainWindow", "Expand All", None, -1))
        self.actionExpand_All.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Expands all the categories", None, -1))
        self.actionExpand_All.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.actionCollapse_All.setText(QtWidgets.QApplication.translate("MainWindow", "Collapse All", None, -1))
        self.actionCollapse_All.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Collapses all the categories", None, -1))
        self.actionCollapse_All.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None, -1))
        self.actionApplyAvalues.setText(QtWidgets.QApplication.translate("MainWindow", "Apply A Values", None, -1))
        self.actionApplyAvalues.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Applies all the values from the profile A", None, -1))
        self.actionApplyAvalues.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+1", None, -1))
        self.actionApplyBValues.setText(QtWidgets.QApplication.translate("MainWindow", "Apply B Values", None, -1))
        self.actionApplyBValues.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Applies all the values from the profile B", None, -1))
        self.actionApplyBValues.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+2", None, -1))
