# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui',
# licensing of '.\main_window.ui' applies.
#
# Created: Mon Apr 29 09:14:42 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_api = QtWidgets.QHBoxLayout()
        self.layout_api.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_api.setContentsMargins(-1, -1, -1, 10)
        self.layout_api.setObjectName("layout_api")
        self.lbl_api = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api.sizePolicy().hasHeightForWidth())
        self.lbl_api.setSizePolicy(sizePolicy)
        self.lbl_api.setObjectName("lbl_api")
        self.layout_api.addWidget(self.lbl_api)
        self.cmb_api = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_api.setEnabled(False)
        self.cmb_api.setMinimumSize(QtCore.QSize(44, 0))
        self.cmb_api.setObjectName("cmb_api")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.layout_api.addWidget(self.cmb_api)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_api.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layout_api)
        self.layout_source = QtWidgets.QHBoxLayout()
        self.layout_source.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_source.setObjectName("layout_source")
        self.lbl_source = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_source.sizePolicy().hasHeightForWidth())
        self.lbl_source.setSizePolicy(sizePolicy)
        self.lbl_source.setMinimumSize(QtCore.QSize(108, 0))
        self.lbl_source.setObjectName("lbl_source")
        self.layout_source.addWidget(self.lbl_source)
        self.le_source = QtWidgets.QLineEdit(self.centralwidget)
        self.le_source.setEnabled(True)
        self.le_source.setReadOnly(True)
        self.le_source.setObjectName("le_source")
        self.layout_source.addWidget(self.le_source)
        self.btn_source = QtWidgets.QToolButton(self.centralwidget)
        self.btn_source.setObjectName("btn_source")
        self.layout_source.addWidget(self.btn_source)
        self.verticalLayout_2.addLayout(self.layout_source)
        self.layout_selector = QtWidgets.QHBoxLayout()
        self.layout_selector.setSpacing(7)
        self.layout_selector.setObjectName("layout_selector")
        self.lbl_target = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_target.sizePolicy().hasHeightForWidth())
        self.lbl_target.setSizePolicy(sizePolicy)
        self.lbl_target.setMinimumSize(QtCore.QSize(108, 0))
        self.lbl_target.setObjectName("lbl_target")
        self.layout_selector.addWidget(self.lbl_target)
        self.le_target = QtWidgets.QLineEdit(self.centralwidget)
        self.le_target.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_target.sizePolicy().hasHeightForWidth())
        self.le_target.setSizePolicy(sizePolicy)
        self.le_target.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.le_target.setReadOnly(True)
        self.le_target.setObjectName("le_target")
        self.layout_selector.addWidget(self.le_target)
        self.btn_target = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_target.sizePolicy().hasHeightForWidth())
        self.btn_target.setSizePolicy(sizePolicy)
        self.btn_target.setObjectName("btn_target")
        self.layout_selector.addWidget(self.btn_target)
        self.verticalLayout_2.addLayout(self.layout_selector)
        self.layout_filter = QtWidgets.QHBoxLayout()
        self.layout_filter.setObjectName("layout_filter")
        self.lbl_filter = QtWidgets.QLabel(self.centralwidget)
        self.lbl_filter.setObjectName("lbl_filter")
        self.layout_filter.addWidget(self.lbl_filter)
        self.cmb_filter = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_filter.sizePolicy().hasHeightForWidth())
        self.cmb_filter.setSizePolicy(sizePolicy)
        self.cmb_filter.setMinimumSize(QtCore.QSize(0, 0))
        self.cmb_filter.setObjectName("cmb_filter")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.layout_filter.addWidget(self.cmb_filter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_filter.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.layout_filter)
        spacerItem2 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.fields_selector = QtWidgets.QGridLayout()
        self.fields_selector.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.fields_selector.setContentsMargins(-1, -1, -1, 0)
        self.fields_selector.setObjectName("fields_selector")
        self.lbl_merged = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_merged.sizePolicy().hasHeightForWidth())
        self.lbl_merged.setSizePolicy(sizePolicy)
        self.lbl_merged.setObjectName("lbl_merged")
        self.fields_selector.addWidget(self.lbl_merged, 0, 3, 1, 1)
        self.list_source = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_source.sizePolicy().hasHeightForWidth())
        self.list_source.setSizePolicy(sizePolicy)
        self.list_source.setAcceptDrops(False)
        self.list_source.setDragEnabled(False)
        self.list_source.setObjectName("list_source")
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        QtWidgets.QListWidgetItem(self.list_source)
        #Unnamed.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        QtWidgets.QListWidgetItem(self.list_source)
        #Unnamed.setBackground(brush)
        #Unnamed.setForeground(brush)
        item = QtWidgets.QListWidgetItem(self.list_source)
        item.setFlags(QtCore.Qt.NoItemFlags)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.BDiagPattern)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        QtWidgets.QListWidgetItem(self.list_source)
        #Unnamed.setBackground(brush)
        #Unnamed.setForeground(brush)
        self.fields_selector.addWidget(self.list_source, 1, 0, 2, 1)
        self.list_target = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_target.sizePolicy().hasHeightForWidth())
        self.list_target.setSizePolicy(sizePolicy)
        self.list_target.setAcceptDrops(False)
        self.list_target.setDragEnabled(False)
        self.list_target.setObjectName("list_target")
        self.fields_selector.addWidget(self.list_target, 1, 1, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fields_selector.addWidget(self.line, 1, 2, 2, 1)
        self.lbl_source_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_source_2.sizePolicy().hasHeightForWidth())
        self.lbl_source_2.setSizePolicy(sizePolicy)
        self.lbl_source_2.setObjectName("lbl_source_2")
        self.fields_selector.addWidget(self.lbl_source_2, 0, 0, 1, 1)
        self.lbl_target_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_target_2.sizePolicy().hasHeightForWidth())
        self.lbl_target_2.setSizePolicy(sizePolicy)
        self.lbl_target_2.setObjectName("lbl_target_2")
        self.fields_selector.addWidget(self.lbl_target_2, 0, 1, 1, 1)
        self.list_merged = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_merged.sizePolicy().hasHeightForWidth())
        self.list_merged.setSizePolicy(sizePolicy)
        self.list_merged.setAcceptDrops(False)
        self.list_merged.setObjectName("list_merged")
        self.fields_selector.addWidget(self.list_merged, 1, 3, 2, 1)
        self.verticalLayout_2.addLayout(self.fields_selector)
        self.layout_merge = QtWidgets.QHBoxLayout()
        self.layout_merge.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_merge.setContentsMargins(-1, -1, -1, 0)
        self.layout_merge.setObjectName("layout_merge")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_merge.addItem(spacerItem3)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(80, 36))
        self.btn_start.setObjectName("btn_start")
        self.layout_merge.addWidget(self.btn_start)
        self.verticalLayout_2.addLayout(self.layout_merge)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmb_api.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cmb_api, self.btn_target)
        MainWindow.setTabOrder(self.btn_target, self.list_source)
        MainWindow.setTabOrder(self.list_source, self.list_target)
        MainWindow.setTabOrder(self.list_target, self.btn_start)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SF Profile Merger by @f1r3f0x -- WIP", None, -1))
        self.lbl_api.setText(QtWidgets.QApplication.translate("MainWindow", "(TODO) Base Api Version:", None, -1))
        self.cmb_api.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "45", None, -1))
        self.cmb_api.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "44", None, -1))
        self.cmb_api.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "43", None, -1))
        self.cmb_api.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "42", None, -1))
        self.cmb_api.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "41", None, -1))
        self.cmb_api.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "40", None, -1))
        self.cmb_api.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "39", None, -1))
        self.cmb_api.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "38", None, -1))
        self.cmb_api.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "37", None, -1))
        self.cmb_api.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "36", None, -1))
        self.cmb_api.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "35", None, -1))
        self.cmb_api.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "34", None, -1))
        self.cmb_api.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "33", None, -1))
        self.cmb_api.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "32", None, -1))
        self.cmb_api.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.lbl_source.setText(QtWidgets.QApplication.translate("MainWindow", "Profile A (Source):", None, -1))
        self.btn_source.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lbl_target.setText(QtWidgets.QApplication.translate("MainWindow", "Profile B (Target):", None, -1))
        self.btn_target.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lbl_filter.setText(QtWidgets.QApplication.translate("MainWindow", "Permission Type:", None, -1))
        self.cmb_filter.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "All", None, -1))
        self.cmb_filter.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "apexClasses", None, -1))
        self.cmb_filter.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "pageAccesses", None, -1))
        self.lbl_merged.setText(QtWidgets.QApplication.translate("MainWindow", "Profile Merged:", None, -1))
        __sortingEnabled = self.list_source.isSortingEnabled()
        self.list_source.setSortingEnabled(False)
        self.list_source.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "Enabled", None, -1))
        self.list_source.item(1).setText(QtWidgets.QApplication.translate("MainWindow", "Disabled", None, -1))
        self.list_source.item(3).setText(QtWidgets.QApplication.translate("MainWindow", "Removed", None, -1))
        self.list_source.setSortingEnabled(__sortingEnabled)
        self.lbl_source_2.setText(QtWidgets.QApplication.translate("MainWindow", "Profile A:", None, -1))
        self.lbl_target_2.setText(QtWidgets.QApplication.translate("MainWindow", "Profile B:", None, -1))
        self.btn_start.setText(QtWidgets.QApplication.translate("MainWindow", "Merge!", None, -1))

