# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_window.ui',
# licensing of '.\ui\main_window.ui' applies.
#
# Created: Fri Jul 26 11:59:58 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from ui import UiTreeWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.layout_main = QtWidgets.QWidget(MainWindow)
        self.layout_main.setEnabled(True)
        self.layout_main.setObjectName("layout_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layout_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_api = QtWidgets.QHBoxLayout()
        self.layout_api.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_api.setContentsMargins(-1, -1, -1, 10)
        self.layout_api.setObjectName("layout_api")
        self.lbl_api = QtWidgets.QLabel(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api.sizePolicy().hasHeightForWidth())
        self.lbl_api.setSizePolicy(sizePolicy)
        self.lbl_api.setObjectName("lbl_api")
        self.layout_api.addWidget(self.lbl_api)
        self.cmb_api = QtWidgets.QComboBox(self.layout_main)
        self.cmb_api.setEnabled(False)
        self.cmb_api.setMinimumSize(QtCore.QSize(44, 0))
        self.cmb_api.setObjectName("cmb_api")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.cmb_api.addItem("")
        self.layout_api.addWidget(self.cmb_api)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_api.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layout_api)
        self.layout_profiles = QtWidgets.QHBoxLayout()
        self.layout_profiles.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_profiles.setContentsMargins(-1, -1, -1, 0)
        self.layout_profiles.setObjectName("layout_profiles")
        self.layout_a = QtWidgets.QHBoxLayout()
        self.layout_a.setSpacing(6)
        self.layout_a.setObjectName("layout_a")
        self.lbl_a = QtWidgets.QLabel(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_a.sizePolicy().hasHeightForWidth())
        self.lbl_a.setSizePolicy(sizePolicy)
        self.lbl_a.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_a.setObjectName("lbl_a")
        self.layout_a.addWidget(self.lbl_a)
        self.le_a = QtWidgets.QLineEdit(self.layout_main)
        self.le_a.setEnabled(True)
        self.le_a.setReadOnly(True)
        self.le_a.setObjectName("le_a")
        self.layout_a.addWidget(self.le_a)
        self.btn_close_a = QtWidgets.QToolButton(self.layout_main)
        self.btn_close_a.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_a.setIcon(icon)
        self.btn_close_a.setObjectName("btn_close_a")
        self.layout_a.addWidget(self.btn_close_a)
        self.btn_a = QtWidgets.QToolButton(self.layout_main)
        self.btn_a.setObjectName("btn_a")
        self.layout_a.addWidget(self.btn_a)
        self.layout_profiles.addLayout(self.layout_a)
        self.btn_merge_dir = QtWidgets.QToolButton(self.layout_main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/icons/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_merge_dir.setIcon(icon1)
        self.btn_merge_dir.setObjectName("btn_merge_dir")
        self.layout_profiles.addWidget(self.btn_merge_dir)
        self.layout_b = QtWidgets.QHBoxLayout()
        self.layout_b.setSpacing(6)
        self.layout_b.setObjectName("layout_b")
        self.btn_b = QtWidgets.QToolButton(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_b.sizePolicy().hasHeightForWidth())
        self.btn_b.setSizePolicy(sizePolicy)
        self.btn_b.setObjectName("btn_b")
        self.layout_b.addWidget(self.btn_b)
        self.btn_close_b = QtWidgets.QToolButton(self.layout_main)
        self.btn_close_b.setEnabled(False)
        self.btn_close_b.setIcon(icon)
        self.btn_close_b.setObjectName("btn_close_b")
        self.layout_b.addWidget(self.btn_close_b)
        self.le_b = QtWidgets.QLineEdit(self.layout_main)
        self.le_b.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_b.sizePolicy().hasHeightForWidth())
        self.le_b.setSizePolicy(sizePolicy)
        self.le_b.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.le_b.setReadOnly(True)
        self.le_b.setObjectName("le_b")
        self.layout_b.addWidget(self.le_b)
        self.lbl_b = QtWidgets.QLabel(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_b.sizePolicy().hasHeightForWidth())
        self.lbl_b.setSizePolicy(sizePolicy)
        self.lbl_b.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_b.setObjectName("lbl_b")
        self.layout_b.addWidget(self.lbl_b)
        self.layout_profiles.addLayout(self.layout_b)
        self.verticalLayout_2.addLayout(self.layout_profiles)
        self.layout_merger = QtWidgets.QGridLayout()
        self.layout_merger.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_merger.setContentsMargins(-1, -1, -1, 0)
        self.layout_merger.setObjectName("layout_merger")
        self.tree_b = QtWidgets.QTreeWidget(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_b.sizePolicy().hasHeightForWidth())
        self.tree_b.setSizePolicy(sizePolicy)
        self.tree_b.setAcceptDrops(False)
        self.tree_b.setDragEnabled(False)
        self.tree_b.setObjectName("tree_b")
        self.layout_merger.addWidget(self.tree_b, 1, 3, 1, 1)
        self.tree_a = QtWidgets.QTreeWidget(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_a.sizePolicy().hasHeightForWidth())
        self.tree_a.setSizePolicy(sizePolicy)
        self.tree_a.setAcceptDrops(False)
        self.tree_a.setStyleSheet("")
        self.tree_a.setDragEnabled(False)
        self.tree_a.setObjectName("tree_a")
        self.layout_merger.addWidget(self.tree_a, 1, 1, 1, 1)
        self.tree_merged = UiTreeWidget(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_merged.sizePolicy().hasHeightForWidth())
        self.tree_merged.setSizePolicy(sizePolicy)
        self.tree_merged.setAcceptDrops(False)
        self.tree_merged.setObjectName("tree_merged")
        self.layout_merger.addWidget(self.tree_merged, 1, 2, 1, 1)
        self.layout_treeButtons = QtWidgets.QHBoxLayout()
        self.layout_treeButtons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_treeButtons.setObjectName("layout_treeButtons")
        self.btn_applyA = QtWidgets.QToolButton(self.layout_main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/icons/chevrons-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_applyA.setIcon(icon2)
        self.btn_applyA.setObjectName("btn_applyA")
        self.layout_treeButtons.addWidget(self.btn_applyA)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_treeButtons.addItem(spacerItem1)
        self.btn_expandAll = QtWidgets.QToolButton(self.layout_main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/icons/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_expandAll.setIcon(icon3)
        self.btn_expandAll.setObjectName("btn_expandAll")
        self.layout_treeButtons.addWidget(self.btn_expandAll)
        self.btn_collapseAll = QtWidgets.QToolButton(self.layout_main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/icons/minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_collapseAll.setIcon(icon4)
        self.btn_collapseAll.setObjectName("btn_collapseAll")
        self.layout_treeButtons.addWidget(self.btn_collapseAll)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_treeButtons.addItem(spacerItem2)
        self.btn_applyB = QtWidgets.QToolButton(self.layout_main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/icons/chevrons-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_applyB.setIcon(icon5)
        self.btn_applyB.setObjectName("btn_applyB")
        self.layout_treeButtons.addWidget(self.btn_applyB)
        self.layout_merger.addLayout(self.layout_treeButtons, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.layout_merger)
        self.layout_filter = QtWidgets.QHBoxLayout()
        self.layout_filter.setSpacing(6)
        self.layout_filter.setObjectName("layout_filter")
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_filter.addItem(spacerItem3)
        self.btn_start = QtWidgets.QPushButton(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(96, 36))
        self.btn_start.setObjectName("btn_start")
        self.layout_filter.addWidget(self.btn_start)
        self.verticalLayout_2.addLayout(self.layout_filter)
        MainWindow.setCentralWidget(self.layout_main)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 24))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.accionPlaceHolder = QtWidgets.QAction(MainWindow)
        self.accionPlaceHolder.setEnabled(False)
        self.accionPlaceHolder.setObjectName("accionPlaceHolder")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setEnabled(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionMerge = QtWidgets.QAction(MainWindow)
        self.actionMerge.setObjectName("actionMerge")
        self.actionExpand_All = QtWidgets.QAction(MainWindow)
        self.actionExpand_All.setObjectName("actionExpand_All")
        self.actionCollapse_All = QtWidgets.QAction(MainWindow)
        self.actionCollapse_All.setObjectName("actionCollapse_All")
        self.actionApplyAvalues = QtWidgets.QAction(MainWindow)
        self.actionApplyAvalues.setObjectName("actionApplyAvalues")
        self.actionApplyBValues = QtWidgets.QAction(MainWindow)
        self.actionApplyBValues.setObjectName("actionApplyBValues")
        self.actionOpenProfileA = QtWidgets.QAction(MainWindow)
        self.actionOpenProfileA.setObjectName("actionOpenProfileA")
        self.actionOpenProfileB = QtWidgets.QAction(MainWindow)
        self.actionOpenProfileB.setObjectName("actionOpenProfileB")
        self.menuSettings.addAction(self.accionPlaceHolder)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionOpenProfileA)
        self.menuFile.addAction(self.actionOpenProfileB)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMerge)
        self.menuView.addAction(self.actionExpand_All)
        self.menuView.addAction(self.actionCollapse_All)
        self.menuEdit.addAction(self.actionApplyAvalues)
        self.menuEdit.addAction(self.actionApplyBValues)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.cmb_api.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cmb_api, self.le_a)
        MainWindow.setTabOrder(self.le_a, self.btn_a)
        MainWindow.setTabOrder(self.btn_a, self.btn_merge_dir)
        MainWindow.setTabOrder(self.btn_merge_dir, self.btn_b)
        MainWindow.setTabOrder(self.btn_b, self.le_b)
        MainWindow.setTabOrder(self.le_b, self.btn_applyA)
        MainWindow.setTabOrder(self.btn_applyA, self.btn_expandAll)
        MainWindow.setTabOrder(self.btn_expandAll, self.btn_collapseAll)
        MainWindow.setTabOrder(self.btn_collapseAll, self.btn_applyB)
        MainWindow.setTabOrder(self.btn_applyB, self.tree_a)
        MainWindow.setTabOrder(self.tree_a, self.tree_merged)
        MainWindow.setTabOrder(self.tree_merged, self.tree_b)
        MainWindow.setTabOrder(self.tree_b, self.btn_start)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SF Profile Merger by @f1r3f0x -- WIP", None, -1))
        self.lbl_api.setText(QtWidgets.QApplication.translate("MainWindow", "(TODO) Base Api Version:", None, -1))
        self.cmb_api.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "45", None, -1))
        self.cmb_api.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "44", None, -1))
        self.cmb_api.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "43", None, -1))
        self.cmb_api.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "42", None, -1))
        self.cmb_api.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "41", None, -1))
        self.cmb_api.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "40", None, -1))
        self.cmb_api.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "39", None, -1))
        self.cmb_api.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "38", None, -1))
        self.cmb_api.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "37", None, -1))
        self.cmb_api.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "36", None, -1))
        self.cmb_api.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "35", None, -1))
        self.cmb_api.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "34", None, -1))
        self.cmb_api.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "33", None, -1))
        self.cmb_api.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "32", None, -1))
        self.cmb_api.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.lbl_a.setText(QtWidgets.QApplication.translate("MainWindow", "Profile A", None, -1))
        self.btn_close_a.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_a.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Load Profile A", None, -1))
        self.btn_a.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_merge_dir.setToolTip(QtWidgets.QApplication.translate("MainWindow", "This will determine which profile values will take priority while merging", None, -1))
        self.btn_merge_dir.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Change merge direction", None, -1))
        self.btn_merge_dir.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_b.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Load Profile B", None, -1))
        self.btn_b.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_close_b.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lbl_b.setText(QtWidgets.QApplication.translate("MainWindow", "Profile B", None, -1))
        self.tree_b.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "[Left Click] to merge Profile B value", None, -1))
        self.tree_b.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Profile B", None, -1))
        self.tree_a.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "[Left Click] to merge Profile A value", None, -1))
        self.tree_a.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Profile A", None, -1))
        self.tree_merged.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "[Right Click] to toggle values | [Left Click] Ignore field in merge", None, -1))
        self.tree_merged.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Profile Merged", None, -1))
        self.btn_applyA.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Apply all A values", None, -1))
        self.btn_applyA.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_expandAll.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Expand All Categories", None, -1))
        self.btn_expandAll.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_collapseAll.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Collapse All Categories", None, -1))
        self.btn_collapseAll.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_applyB.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Apply all B values", None, -1))
        self.btn_applyB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_start.setText(QtWidgets.QApplication.translate("MainWindow", "Merge and Save", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "?", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.accionPlaceHolder.setText(QtWidgets.QApplication.translate("MainWindow", "TODO", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionMerge.setText(QtWidgets.QApplication.translate("MainWindow", "Merge", None, -1))
        self.actionMerge.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Create merged profile and save", None, -1))
        self.actionMerge.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionExpand_All.setText(QtWidgets.QApplication.translate("MainWindow", "Expand All", None, -1))
        self.actionExpand_All.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Expands all the categories", None, -1))
        self.actionExpand_All.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.actionCollapse_All.setText(QtWidgets.QApplication.translate("MainWindow", "Collapse All", None, -1))
        self.actionCollapse_All.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Collapses all the categories", None, -1))
        self.actionCollapse_All.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None, -1))
        self.actionApplyAvalues.setText(QtWidgets.QApplication.translate("MainWindow", "Apply A Values", None, -1))
        self.actionApplyAvalues.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Applies all the values from the profile A", None, -1))
        self.actionApplyAvalues.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+1", None, -1))
        self.actionApplyBValues.setText(QtWidgets.QApplication.translate("MainWindow", "Apply B Values", None, -1))
        self.actionApplyBValues.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Applies all the values from the profile B", None, -1))
        self.actionApplyBValues.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+2", None, -1))
        self.actionOpenProfileA.setText(QtWidgets.QApplication.translate("MainWindow", "Open Profile A", None, -1))
        self.actionOpenProfileA.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+1", None, -1))
        self.actionOpenProfileB.setText(QtWidgets.QApplication.translate("MainWindow", "Open Profile B", None, -1))
        self.actionOpenProfileB.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Profile B", None, -1))
        self.actionOpenProfileB.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+2", None, -1))
